apiVersion: apps/v1
kind: Deployment
metadata:
  name: weight-tracker-deployment
  labels:
    apps: weight-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weight-tracker
  template:
    metadata:
      labels:
        app: weight-tracker
    spec:
      volumes:
        - name: config
          configMap:
            name: weight-tracker-config
            items:
              - key: "Rocket.toml"
                path: "Rocket.toml"
      containers:
        - name: weight-tracker
          image: 10.42.0.101:32000/weight-tracker:latest
          ports:
            - containerPort: 8000
          env:
            - name: ROCKET_CONFIG
              value: /app/data/Rocket.toml
          volumeMounts:
            - name: config
              mountPath: /app/data
              readOnly: true
          command: ["./weight-tracker"]
